const stellarAssets = [
  {
    code: "XLM",
    issuer: "native",
    contract: "CAS3J7GYLGXMF6TDJBBYYSE3HQ6BBSMLNUQ34T6TZMYMW2EVH34XOWMA",
    name: "XLM",
    org: "Stellar Lumens Foundation",
    domain: "stellar.org",
    icon: "https://stellar.myfilebase.com/ipfs/QmSTXU2wn1USnmd5ZypA5zMze259wEPSDP3i8wivyr9qiq",
    decimals: 7,
  },
  {
    code: "USDC",
    issuer: "GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN",
    contract: "CCW67TSZV3SSS2HXMBQ5JFGCKJNXKZM7UQUWUZPUTHXSTZLEO7SJMI75",
    name: "USD Coin",
    org: "Centre Consortium LLC dba Centre Consortium",
    domain: "centre.io",
    icon: "https://stellar.myfilebase.com/ipfs/QmNcfZxs8e9uVyhEa3xoPWCsj3ZogGirtixMEC9Km4Fjm2",
    decimals: 7,
  },
  {
    code: "AQUA",
    issuer: "GBNZILSTVQZ4R7IKQDGHYGY2QXL5QOFJYQMXPKWRRM5PAV7Y4M67AQUA",
    contract: "CAUIKL3IYGMERDRUN6YSCLWVAKIFG5Q4YJHUKM4S4NJZQIA3BAS6OJPK",
    name: "AQUA",
    org: "Aquarius dba AQUA token",
    domain: "aqua.network",
    icon: "https://stellar.myfilebase.com/ipfs/QmTqE6DhQftp51YXXL8HtkEBhr1PpW6F8W1NxnVoyK6G93",
    decimals: 7,
  },
  {
    code: "yXLM",
    issuer: "GARDNV3Q7YGT4AKSDF25LT32YSCCW4EV22Y2TV3I2PU2MMXJTEDL5T55",
    contract: "CBZVSNVB55ANF24QVJL2K5QCLOAB6XITGTGXYEAF6NPTXYKEJUYQOHFC",
    name: "yXLM",
    org: "Ultra Capital LLC dba Ultra Capital",
    domain: "ultracapital.xyz",
    icon: "https://stellar.myfilebase.com/ipfs/QmSTXU2wn1USnmd5ZypA5zMze259wEPSDP3i8wivyr9qiq",
    decimals: 7,
  },

  {
    code: "SSLX",
    issuer: "GBHFGY3ZNEJWLNO4LBUKLYOCEK4V7ENEBJGPRHHX7JU47GWHBREH37UR",
    contract: "CBHBD77PWZ3AXPQVYVDBHDKEMVNOR26UZUZHWCB6QC7J5SETQPRUQAS4",
    name: "SSLX",
    org: "Cassator Corp.",
    domain: "sslx.sl8.online",
    icon: "https://stellar.myfilebase.com/ipfs/QmYkosLbMRMPZSiRZBUuCBaGRbaxiuxPmXeFfs6QYeSWCY",
    decimals: 7,
  },
  {
    code: "yUSDC",
    issuer: "GDGTVWSM4MGS4T7Z6W4RPWOCHE2I6RDFCIFZGS3DOA63LWQTRNZNTTFF",
    contract: "CDOFW7HNKLUZRLFZST4EW7V3AV4JI5IHMT6BPXXSY2IEFZ4NE5TWU2P4",
    name: "yUSDC",
    org: "Ultra Capital LLC dba Ultra Capital",
    domain: "ultracapital.xyz",
    icon: "https://stellar.myfilebase.com/ipfs/QmTmcN7qNDkcfaawoJCUv31aWjwT75KjKAX4zC7JFrE2Xr",
    decimals: 7,
  },

  {
    code: "XRP",
    issuer: "GBXRPL45NPHCVMFFAYZVUVFFVKSIZ362ZXFP7I2ETNQ3QKZMFLPRDTD5",
    contract: "CAAV3AE3VKD2P4TY7LWTQMMJHIJ4WOCZ5ANCIJPC3NRSERKVXNHBU2W7",
    name: "XRP",
    org: "Muyu Network",
    domain: "fchain.io",
    icon: "https://stellar.myfilebase.com/ipfs/QmPYsJjR623oATjwfLtnqW4BEDAgBsnMktjXcLC2pfNiEm",
    decimals: 7,
  },
  {
    code: "BTCLN",
    issuer: "GDPKQ2TSNJOFSEE7XSUXPWRP27H6GFGLWD7JCHNEYYWQVGFA543EVBVT",
    contract: "CBHIQPUXLFLC5O44ZJVUTCL5LMZFLVGU5DEIGSYKBSAPFMOGTKOQEPFM",
    name: "Bitcoin Lightning",
    org: "KB Trading",
    domain: "kbtrading.org",
    icon: "https://stellar.myfilebase.com/ipfs/QmVrLfcrZ5L2NeWoeTqDjpoTw9C86C5GHzNxXHXovo3Ztq",
    decimals: 7,
  },
  {
    code: "ARST",
    issuer: "GCSAZVWXZKWS4XS223M5F54H2B6XPIIXZZGP7KEAIU6YSL5HDRGCI3DG",
    contract: "CCRPYMVKZLWGZHEDZ23FOE22E3T3HOCNP5Y2EFZFVRUVIXU5NJ7UNGV2",
    name: "ARST",
    org: "Relay Tech Services Ltd",
    domain: "pubnet-sep.latamex.com",
    decimals: 7,
  },
  {
    code: "IDRT",
    issuer: "GDPKQ2TSNJOFSEE7XSUXPWRP27H6GFGLWD7JCHNEYYWQVGFA543EVBVT",
    contract: "CDYBK2X5ZEQ7ZNDN7IPWWMOQ6SWEJW4A4UE2PNDFDVCYNAXB64O4FNXX",
    name: "Indonesian IDRT",
    org: "KB Trading",
    domain: "kbtrading.org",
    icon: "https://stellar.myfilebase.com/ipfs/Qme7voiVGkuBJRR2ZMSWFdrfJ94tqGH8tLBaCHk8BaUxhn",
    decimals: 7,
  },
  {
    code: "BTC",
    issuer: "GDPJALI4AZKUU2W426U5WKMAT6CN3AJRPIIRYR2YM54TL2GDWO5O2MZM",
    contract: "CAO7DDJNGMOYQPRYDY5JVZ5YEK4UQBSMGLAEWRCUOTRMDSBMGWSAATDZ",
    name: "BTC",
    org: "Ultra Capital LLC dba Ultra Capital",
    domain: "ultracapital.xyz",
    icon: "https://stellar.myfilebase.com/ipfs/QmUjsGiNcUFTbiKoMZyBtgkSwfndBXSbRKFpGrYKvHC1fX",
    decimals: 7,
  },
  {
    code: "ETH",
    issuer: "GBFXOHVAS43OIWNIO7XLRJAHT3BICFEIKOJLZVXNT572MISM4CMGSOCC",
    contract: "CBH4M45TQBLDPXOK6L7VYKMEJWFITBOL64BN3WDAIIDT4LNUTWTTOCKF",
    name: "ETH",
    org: "Ultra Capital LLC dba Ultra Capital",
    domain: "ultracapital.xyz",
    icon: "https://stellar.myfilebase.com/ipfs/Qmdu8ywKeXkkGWE1EoUxwuGUZRaDs2rG9ZsV8d6F4NLMxQ",
    decimals: 7,
  },
  {
    code: "SHX",
    issuer: "GDSTRSHXHGJ7ZIVRBXEYE5Q74XUVCUSEKEBR7UCHEUUEK72N7I7KJ6JH",
    contract: "CCKCKCPHYVXQD4NECBFJTFSCU2AMSJGCNG4O6K4JVRE2BLPR7WNDBQIQ",
    name: "Stronghold SHx",
    org: "Stronghold",
    domain: "stronghold.co",
    icon: "https://stellar.myfilebase.com/ipfs/QmX2Jn7gzyL27vP6hWrDTpwFeLcuUz7jcLK2ovhMrUAQVp",
    decimals: 7,
  },
  {
    code: "BRL",
    issuer: "GDVKY2GU2DRXWTBEYJJWSFXIGBZV6AZNBVVSUHEPZI54LIS6BA7DVVSP",
    contract: "CBF4E5GSTVSITE5Q2ENOTEUQJPBZAU3SBDVLQMSQ7GLBRTSYGUAT722K",
    name: "Brazilian Real",
    org: "nTokens Servios Digitais Ltda",
    domain: "ntokens.com",
    icon: "https://stellar.myfilebase.com/ipfs/Qmdz4nG4DpdQxjmdqLUM34VPdvU797gLekDr3oiX4ZqMeP",
    decimals: 7,
  },
  {
    code: "yBTC",
    issuer: "GBUVRNH4RW4VLHP4C5MOF46RRIRZLAVHYGX45MVSTKA2F6TMR7E7L6NW",
    contract: "CB2XMFB6BDIHFOSFB5IXHDOYV3SI3IXMNIZLPDZHC7ENDCXSBEBZAO2Y",
    name: "yBTC",
    org: "Ultra Capital LLC dba Ultra Capital",
    domain: "ultracapital.xyz",
    icon: "https://stellar.myfilebase.com/ipfs/QmT8LZrzaxnxAKgANZhUcK43SahGjkKaZ37vEGp3qs5X1R",
    decimals: 7,
  },
  {
    code: "XCHF",
    issuer: "GDPKQ2TSNJOFSEE7XSUXPWRP27H6GFGLWD7JCHNEYYWQVGFA543EVBVT",
    contract: "CACFQEH2USDRGSBYFOVJMX4DMX7HMRYAYOV2IWR7XEX3DD3HYQEWPAAL",
    name: "Swiss Franc",
    org: "KB Trading",
    domain: "kbtrading.org",
    icon: "https://stellar.myfilebase.com/ipfs/QmfUfypiaSegTjHTzWGPUGfhBFCvWsnGEkaDmfQdWyXmXi",
    decimals: 7,
  },
  {
    code: "XRP",
    issuer: "GCNSGHUCG5VMGLT5RIYYZSO7VQULQKAJ62QA33DBC5PPBSO57LFWVV6P",
    contract: "CBSEMU4NLPURIO37O5KNATEIHGY2BTF27PBJH46H5ESRB7MREGWNMYKJ",
    name: "Ripple",
    org: "Interstellar, Inc.",
    domain: "interstellar.exchange",
    icon: "https://stellar.myfilebase.com/ipfs/QmPME2PGmRbDJb3z7ZSdjaboXkR4FhBgu785cenj1ogm6R",
    decimals: 7,
  },
  {
    code: "SCOP",
    issuer: "GC6OYQJIZF3HFXCYPFCBXYXNGIBQ4TNSFUBUXQJOZWIP6F3YZK4QH3VQ",
    contract: "CCJVS6IVXAAXWCMFVK6QLWHZHR4RTVRSEZRQ53GOAEDN3VY2BLPVY72J",
    name: "Scopuly",
    org: "Scopuly",
    domain: "scopuly.com",
    icon: "https://stellar.myfilebase.com/ipfs/QmXUQsnLxb5PA7iPby2JnP23mCHSbXxf7Kr5QdfmhYzaDQ",
    decimals: 7,
  },
  {
    code: "ARS",
    issuer: "GCYE7C77EB5AWAA25R5XMWNI2EDOKTTFTTPZKM2SR5DI4B4WFD52DARS",
    contract: "CCD6H4LBTHAPY3NGEE6TLLRUSPJGX4K5XI2J6E4MUNDB5TNXEKC23H5B",
    name: "Peso Digital",
    org: "Grupo Anchor S.A. dba Anclap",
    domain: "api.anclap.com",
    icon: "https://stellar.myfilebase.com/ipfs/QmRGEnqdULKdDc6X3Qa7E216ZTitvnwEZ4zkASP8jik4uK",
    decimals: 7,
  },
  {
    code: "EURMTL",
    issuer: "GACKTN5DAZGWXRWB2WLM6OPBDHAMT6SJNGLJZPQMEZBUR4JUGBX2UK7V",
    contract: "CDUYP3U6HGTOBUNQD2WTLWNMNADWMENROKZZIHGEVGKIU3ZUDF42CDOK",
    name: "EURMTL",
    org: "Montelibero dba Montelibero",
    domain: "mtl.montelibero.org",
    icon: "https://stellar.myfilebase.com/ipfs/QmPVfGsrsTuQbD3q9SN8ZcrzrsByrpY5tJ6p6rPqpDG2dQ",
    decimals: 7,
  },
  {
    code: "EURC",
    issuer: "GAQRF3UGHBT6JYQZ7YSUYCIYWAF4T2SAA5237Q5LIQYJOHHFAWDXZ7NM",
    contract: "CBVDRT5474OBUEXF5MJB3UGQ5CG7CKGCAH5M4RV5NBCDJUBZ5OXHJLOU",
    name: "EURo Coin",
    org: "MYKOBO",
    domain: "mykobo.co",
    icon: "https://stellar.myfilebase.com/ipfs/QmVMhyjyTimsfHkzwMZfxz3P1zYmwtumCpVkaTBdstb4u1",
    decimals: 7,
  },
  {
    code: "NGNT",
    issuer: "GAWODAROMJ33V5YDFY3NPYTHVYQG7MJXVJ2ND3AOGIHYRWINES6ACCPD",
    contract: "CDCSVQEMYBNK7URICI77CENLP23OIM4AAXUIJ32Z6V3ZT3QXCP2HJXD7",
    name: "Naira Token",
    org: "Cowrie Integrated Systems dba Cowrie Exchange",
    domain: "cowrie.exchange",
    icon: "https://stellar.myfilebase.com/ipfs/QmTa5s8qxAFMGyiHBtGGMTDd3E3uQaex4ajtUB6536JYbR",
    decimals: 7,
  },
  {
    code: "BTC",
    issuer: "GBVOL67TMUQBGL4TZYNMY3ZQ5WGQYFPFD5VJRWXR72VA33VFNL225PL5",
    contract: "CAIRIR3ITE2KNBWHRIAOBBZ2AHIKU5BVTKFTW5IYCOAENR4L5T2THGN6",
    name: "Bitcoin",
    org: "unknown",
    domain: "stellarport.io",
    icon: "https://stellar.myfilebase.com/ipfs/QmZ1BjXaPBiiqD4tdMWdk5Gm5W456ULmPkyPaPMVPmewpS",
    decimals: 7,
  },
  {
    code: "FIDR",
    issuer: "GBZQNUAGO4DZFWOHJ3PVXZKZ2LTSOVAMCTVM46OEMWNWTED4DFS3NAYH",
    contract: "CDDQRIGZRK6Z6ILV4P276HL7D3P63GFW6HBA4N4YXDMFHZ2M4VZGVYRW",
    name: "FIDR",
    org: "Fixedidr dba Cryptoasset and cryptocurrency developer.",
    domain: "fixedidr.com",
    icon: "https://stellar.myfilebase.com/ipfs/QmQCvzWgWGABWpDpnjW8VUuAgpi2wsjTjE3diUrPssEJys",
    decimals: 7,
  },
  {
    code: "XXA",
    issuer: "GC4HS4CQCZULIOTGLLPGRAAMSBDLFRR6Y7HCUQG66LNQDISXKIXXADIM",
    contract: "CBBJTE34KZHJACB2A6OXCRTDDLX4LI7GKYYD6XYJSGMX46BLNAG752HS",
    name: "IXINIUM",
    org: "Baltic Representative Office dba Ixinium",
    domain: "ixinium.io",
    icon: "https://stellar.myfilebase.com/ipfs/QmZauxoyfmHVomV6DC3KHTwNws6LTskJDbZUG6THVzeCvE",
    decimals: 7,
  },
  {
    code: "yETH",
    issuer: "GDYQNEF2UWTK4L6HITMT53MZ6F5QWO3Q4UVE6SCGC4OMEQIZQQDERQFD",
    contract: "CDYEOOVL6WV4JRY45CXQKOBJFFAPOM5KNQCCDNM333L6RM2L4RO3LKYG",
    name: "yETH",
    org: "Ultra Capital LLC dba Ultra Capital",
    domain: "ultracapital.xyz",
    icon: "https://stellar.myfilebase.com/ipfs/QmavC22bVfCkzHX2AJQZAh6Vbw83JtKDZhKZFUcktomdQn",
    decimals: 7,
  },
  {
    code: "MTL",
    issuer: "GACKTN5DAZGWXRWB2WLM6OPBDHAMT6SJNGLJZPQMEZBUR4JUGBX2UK7V",
    contract: "CAUXAGXTHTCS4RRJC2XDMP77UQMA75BZP4WTXRRBCJGUIRTXZZPS6XGB",
    name: "MTL",
    org: "Montelibero dba Montelibero",
    domain: "mtl.montelibero.org",
    icon: "https://stellar.myfilebase.com/ipfs/QmNwTv3bi45JQrMQHfSKWK3WF4W7cF4QgRtShfWpfqHC75",
    decimals: 7,
  },
  {
    code: "LSP",
    issuer: "GAB7STHVD5BDH3EEYXPI3OM7PCS4V443PYB5FNT6CFGJVPDLMKDM24WK",
    contract: "CBXE6V454EUYWVQCI4TCSOG4CSNPQ2BLYOTKAKXYFHO3KNVX4CXYCY2T",
    name: "Lumenswap asset",
    org: "Lumenswap LLC dba Lumenswap",
    domain: "lumenswap.io",
    icon: "https://stellar.myfilebase.com/ipfs/QmUxVdZomJzT5AQpS9iCuV2h9DTWhy4mh9naMghiHnXRSv",
    decimals: 7,
  },
  {
    code: "MOBI",
    issuer: "GA6HCMBLTZS5VYYBCATRBRZ3BZJMAFUDKYYF6AH6MVCMGWMRDNSWJPIH",
    contract: "CATHRLMZW3JUIYSXYE4YAI3SBBBQGXYAP674RINGUBQLNFTCZHMI5XZJ",
    name: "Mobius",
    org: "Mochi, Inc. dba Mobius Network",
    domain: "mobius.network",
    decimals: 7,
  },
  {
    code: "BTC",
    issuer: "GCNSGHUCG5VMGLT5RIYYZSO7VQULQKAJ62QA33DBC5PPBSO57LFWVV6P",
    contract: "CBJ6JFEMRMSGMOT2CUH3JIKW7AOOZW3HMFNBQFEVHHCE76PWEXAQAJDB",
    name: "Bitcoin",
    org: "Interstellar, Inc.",
    domain: "interstellar.exchange",
    icon: "https://stellar.myfilebase.com/ipfs/QmPp21G3EX3hgwQmhphXDbE15pDBxBtdhuvT28Ah99oYVR",
    decimals: 7,
  },
  {
    code: "LTC",
    issuer: "GCNSGHUCG5VMGLT5RIYYZSO7VQULQKAJ62QA33DBC5PPBSO57LFWVV6P",
    contract: "CCWVP5HVC2TSRNLONGRVS7UK47ORIPURNAGFQ3VR6DP2B77E67QV6P7B",
    name: "Litecoin",
    org: "Interstellar, Inc.",
    domain: "interstellar.exchange",
    icon: "https://stellar.myfilebase.com/ipfs/QmdteyD2DNLYteqDmKEgDwB7zjccYzJ7eQoVTSGQRpAz8q",
    decimals: 7,
  },
  {
    code: "XRP",
    issuer: "GBVOL67TMUQBGL4TZYNMY3ZQ5WGQYFPFD5VJRWXR72VA33VFNL225PL5",
    contract: "CBPMFYWP4FFV7PQUYHXJZBXS75EHR6FXYSYEZWH2UM7AUYSKI2Z3PTCG",
    name: "Ripple",
    org: "unknown",
    domain: "stellarport.io",
    icon: "https://stellar.myfilebase.com/ipfs/QmXb1fhnhzoni3PyYwAPmT2ZbjE5xJptxuRU8H5NjrDGPR",
    decimals: 7,
  },
  {
    code: "USD",
    issuer: "GDUKMGUGDZQK6YHYA5Z6AY2G4XDSZPSZ3SW5UN3ARVMO6QSRDWP5YLEX",
    contract: "CCEBHXWHT2UX6QQ7WZOV6KRGUILICPRFOZD2CEAHZ5AYX7EFW3RG6I2F",
    name: "US Dollar",
    org: "AnchorCoin LLC dba AnchorUSD",
    domain: "stablecoin.anchorusd.com",
    icon: "https://stellar.myfilebase.com/ipfs/QmS1GJpv1T2JwiBaXKDyNLP55NQJN8GAfgdEMdSP7ByWuf",
    decimals: 7,
  },
  {
    code: "VELO",
    issuer: "GDM4RQUQQUVSKQA7S6EM7XBZP3FCGH4Q7CL6TABQ7B2BEJ5ERARM2M5M",
    contract: "CAESLMGW5LYTIEJI7FJHK6SFSWRELLNVX5Q4WR4UZEALMTRWQDBKDPAG",
    name: "VELO",
    org: "unknown",
    decimals: 7,
  },
  {
    code: "AFR",
    issuer: "GBX6YI45VU7WNAAKA3RBFDR3I3UKNFHTJPQ5F6KOOKSGYIAM4TRQN54W",
    contract: "CCG27OZ5AV4WUXS6XTECWAXEY5UOMEFI2CWFA3LHZGBTLYZWTJF3MJYQ",
    name: "AFREUM",
    org: "Afreum DAO dba Afreum",
    domain: "afreum.com",
    icon: "https://stellar.myfilebase.com/ipfs/QmRGezPHkaVJuqxDebHrfqEeESLbEDY3m596wnCWrdCaXw",
    decimals: 7,
  },
  {
    code: "CLPX",
    issuer: "GDYSPBVZHPQTYMGSYNOHRZQNLB3ZWFVQ2F7EP7YBOLRGD42XIC3QUX5G",
    contract: "CBDRPADR3KIBJNUBNRTTO4P7NO5RVPMYKRJB5YCZUZ6B66RKYK324UJY",
    name: "Chilean PESO",
    org: "CLPX S.A.",
    domain: "clpx.finance",
    icon: "https://stellar.myfilebase.com/ipfs/QmPnLPffNmgoACztbEH8Hf7FCSMwyVdaoJni1UmrVkixJB",
    decimals: 7,
  },
  {
    code: "ETH",
    issuer: "GBVOL67TMUQBGL4TZYNMY3ZQ5WGQYFPFD5VJRWXR72VA33VFNL225PL5",
    contract: "CDZNTXPXR2I7VFDBYBADK2DE2SSGQ3DTXT5MJDCTYUMNVFK3CWG5NVC7",
    name: "Ethereum",
    org: "unknown",
    domain: "stellarport.io",
    icon: "https://stellar.myfilebase.com/ipfs/QmTHDNfvxQNyzmMfgPjRFTXfE9RniWFvNuBnU9dpuR9cWz",
    decimals: 7,
  },
  {
    code: "TZS",
    issuer: "GA2MSSZKJOU6RNL3EJKH3S5TB5CDYTFQFWRYFGUJVIN5I6AOIRTLUHTO",
    contract: "CD2GNQFE3GRUY5LRE5WT26OQIUBUQ5YKRVDRQ3FWCW7A7NZAPPFIHFAY",
    name: "Tanzania Shilling",
    org: "ClickPesa Limited dba ClickPesa",
    domain: "connect.clickpesa.com",
    icon: "https://stellar.myfilebase.com/ipfs/QmYjpDbMRGCPGauvM6PWF2DbdayYZpHqopJ4SmXXbmg5nC",
    decimals: 7,
  },
  {
    code: "RIO",
    issuer: "GBNLJIYH34UWO5YZFA3A3HD3N76R6DOI33N4JONUOHEEYZYCAYTEJ5AK",
    contract: "CB2XLDU74PIXO5DENULX53IIC3DMKGN2UM5IBGMSSI634IAQJ7O3Z3UQ",
    name: "Realio Token",
    org: "Realio Network LTD dba Realio",
    domain: "realio.fund",
    icon: "https://stellar.myfilebase.com/ipfs/QmcFrciJP4GdxsVhYTL7DSVsD3C2H2bUj8hNAGRomFB8j9",
    decimals: 7,
  },
  {
    code: "TFT",
    issuer: "GBOVQKJYHXRR3DX6NOX2RRYFRCUMSADGDESTDNBDS6CDVLGVESRTAC47",
    contract: "CCXY3CNHSU2DPUOZFKNNH67IVRMBRCATX4SABDSLBY5LAJI66LRLHTJQ",
    name: "Threefold Token",
    org: "Threefold foundation",
    domain: "threefold.io",
    icon: "https://stellar.myfilebase.com/ipfs/Qmb1bNmAaXCmTWPqE9s1QUg1jmpkkoyzakzdFQUpRLyB2z",
    decimals: 7,
  },
  {
    code: "PEN",
    issuer: "GA4TDPNUCZPTOHB3TKUYMDCRVATXKEADH7ZEYEBWJKQKE2UBFCYNBPEN",
    contract: "CCFS6UDFSR5OJIN45RQPUCZ5JTTU5TQOTIS6XKYKNWKC4TVR752BOWOF",
    name: "Sol Digital",
    org: "Grupo Anchor S.A. dba Anclap",
    domain: "api.anclap.com",
    icon: "https://stellar.myfilebase.com/ipfs/QmdDUupGoc9dBh1U87N34evGxsdBaCGJEvqJo2JcPjTG8w",
    decimals: 7,
  },
  {
    code: "XTAR",
    issuer: "GAORYJ3KBDGIM7FFSKVUJHJ5NEFWIRDIAGGBJBJS7TY6ECZS53257IG4",
    contract: "CDCKFBZYF2AQCSM3JOF2ZM27O3Y6AJAI4OTCQKAFNZ3FHBYUTFOKICIY",
    name: "XTAR",
    org: "Dogstarcoin",
    domain: "dogstarcoin.com",
    icon: "https://stellar.myfilebase.com/ipfs/QmVWgZkt7q9d1JWphqrBe7XTSQfgrJks9Y4joyB94w1RL7",
    decimals: 7,
  },
  {
    code: "ZARZ",
    issuer: "GAROH4EV3WVVTRQKEY43GZK3XSRBEYETRVZ7SVG5LHWOAANSMCTJBB3U",
    contract: "CDXKEC5ADOVKR7U3BO3FV5DUODEFH5VFYCHZ5IXXQ6FI2VO6A36COPFG",
    name: "zeam ZAR",
    org: "ZEAM MINT PTY LTD dba ZEAM MONEY",
    domain: "mint.zeam.money",
    icon: "https://stellar.myfilebase.com/ipfs/QmNpETsegyBpKB7B5kPBbKhDEdbfvjJwAf6KbpjmWDwi7D",
    decimals: 7,
  },
  {
    code: "BTC",
    issuer: "GAUTUYY2THLF7SGITDFMXJVYH3LHDSMGEAKSBU267M2K7A3W543CKUEF",
    contract: "CATJTQ2RWJ5VETWM7R3D43EZ55RUCOJTWV6FO4ACOKYLIRU52K3OBF6S",
    name: "Bitcoin",
    org: "unknown",
    domain: "dead.apay.io",
    icon: "https://stellar.myfilebase.com/ipfs/QmaLi9tq9XZvzVMGg7ezR2Pk46VAgdFXDFtPwNtQmfD6WZ",
    decimals: 7,
  },
  {
    code: "DOGE",
    issuer: "GCNSGHUCG5VMGLT5RIYYZSO7VQULQKAJ62QA33DBC5PPBSO57LFWVV6P",
    contract: "CANAR73IVQTLPJO7XH5TCJ6VXNGT2K7MRPWMXT4GH7433BF7OWBAHJKJ",
    name: "Dogecoin",
    org: "Interstellar, Inc.",
    domain: "interstellar.exchange",
    icon: "https://stellar.myfilebase.com/ipfs/QmUmNpQU5Rx1TGQ2qVY3dgnnZviX7WAEu63nkVFXnS8NJn",
    decimals: 7,
  },
  {
    code: "iFIDR",
    issuer: "GBVVM7ZYANANRP3DWVRANRDUU4M7J5W77EDTSZFD62LQ7SOHJD5IFIDR",
    contract: "CDTHHEDO2YPVXEHZZA3MW5IYECGEM3MF7THR3H7TLDFD6PYPKMAMF6GJ",
    name: "iFIDR",
    org: "Fixedidr dba Cryptoasset and cryptocurrency developer.",
    domain: "fixedidr.com",
    icon: "https://stellar.myfilebase.com/ipfs/QmdbQ2WfRPjJtmMUs6hCWN21oc8Yzqf4osxsHMaBjfy4F6",
    decimals: 7,
  },
  {
    code: "USDM",
    issuer: "GDHDC4GBNPMENZAOBB4NCQ25TGZPDRK6ZGWUGSI22TVFATOLRPSUUSDM",
    contract: "CDKLJRIL7E2OWHTPTIHCAXTXI6PEXFOS6PJFAFCDBYWDT3B3QI42EOJA",
    name: "USD Montelibero",
    org: "Montelibero dba Montelibero",
    domain: "mtl.montelibero.org",
    icon: "https://stellar.myfilebase.com/ipfs/QmcJSKfJDBXTxy83kQMCMqfDKqAZMrJhqWwdob6nZDpfSC",
    decimals: 7,
  },
  {
    code: "FRED",
    issuer: "GCA73U2PZFWAXJSNVMEVPNPPJCZGETWPWZC6E4DJAIWP3ZW3BAGYZLV6",
    contract: "CDGLDM5N34GBRCALDBKVVV4ACVS2TWZLUSMILM32FPIMPHLUUIIRTCNF",
    name: "FRED Energy",
    org: "FRED ENERGY Ltd",
    domain: "fredenergy.org",
    icon: "https://stellar.myfilebase.com/ipfs/QmZghb6aFkhNNEzrZNErh3RSeUXMCHNYFxhLgfWUov3t3h",
    decimals: 7,
  },
  {
    code: "KES",
    issuer: "GA2MSSZKJOU6RNL3EJKH3S5TB5CDYTFQFWRYFGUJVIN5I6AOIRTLUHTO",
    contract: "CBAANNZVSOH6I42ZVVFTVB2JNVSHVBYUDWGGJHB4BLCXARYTNN3ODU3F",
    name: "Kenya Shilling",
    org: "ClickPesa Limited dba ClickPesa",
    domain: "connect.clickpesa.com",
    icon: "https://stellar.myfilebase.com/ipfs/QmYjpDbMRGCPGauvM6PWF2DbdayYZpHqopJ4SmXXbmg5nC",
    decimals: 7,
  },
  {
    code: "Apay",
    issuer: "GBDKPRMOLDHTVUFTQATMMFUBKRI372YPUTOSEH5SZAFRAAVADTUGSSMA",
    contract: "CAIDUWYDM25GBIQVQQ5C7EFVLL2AKX35L6265ZOW2UKINZ6X6IYPDLZ4",
    name: "Authentic-Payment",
    org: "Authentic-Payment",
    domain: "authenticpayment.stellarmint.io",
    icon: "https://stellar.myfilebase.com/ipfs/QmYCk46ev5JvcGwtZVJGavFoGfADd4zktHZVncRmJwyeHP",
    decimals: 7,
  },
  {
    code: "SDEXEX",
    issuer: "GBQHMDRWV3WU5YACBUUCBY4Y6PPWBJXW5WCSG5XJ63FC4HXJNGXYFD5J",
    contract: "CDOIEBW5LN7T7PSFY6ADLPIDF52PFRX57WIYWJ637PCZ7ZFDDN5T6NCH",
    name: "SDEX Explorer Token",
    org: "SDEX Explorer",
    domain: "sdexexplorer.com",
    icon: "https://stellar.myfilebase.com/ipfs/QmPQ1EWMMHvEbTyABUi21DqJw8VznFu5ZtqYydLLZQ36tA",
    decimals: 7,
  },
];

const soroswapList = [
  {
    name: "XRP by Muyu Network",
    code: "XRP",
    issuer: "GBXRPL45NPHCVMFFAYZVUVFFVKSIZ362ZXFP7I2ETNQ3QKZMFLPRDTD5",
    contract: "CAAV3AE3VKD2P4TY7LWTQMMJHIJ4WOCZ5ANCIJPC3NRSERKVXNHBU2W7",
    org: "Muyu Network",
    domain: "fchain.io",
    icon: "https://ipfs.io/ipfs/bafkreih6jv72q2zuthweyyzq5vqu4dcnxbkefd7o7shgs2llnqrdeufyiy",
    decimals: 7,
  },
  {
    code: "CETES",
    issuer: "GCRYUGD5NVARGXT56XEZI5CIFCQETYHAPQQTHO2O3IQZTHDH4LATMYWC",
    contract: "CAL6ER2TI6CTRAY6BFXWNWA7WTYXUXTQCHUBCIBU5O6KM3HJFG6Z6VXV",
    name: "Etherfuse CETES",
    org: "Etherfuse",
    domain: "etherfuse.com",
    icon: "https://stablebonds.s3.us-west-2.amazonaws.com/stablebond/spl-cetes.png",
    decimals: 7,
  },
  {
    name: "BTC by Ultra Capital",
    code: "BTC",
    issuer: "GDPJALI4AZKUU2W426U5WKMAT6CN3AJRPIIRYR2YM54TL2GDWO5O2MZM",
    contract: "CAO7DDJNGMOYQPRYDY5JVZ5YEK4UQBSMGLAEWRCUOTRMDSBMGWSAATDZ",
    org: "Ultra Capital LLC",
    domain: "ultracapital.xyz",
    icon: "https://ipfs.io/ipfs/bafkreidhjwrkvsvuixny3j6w2xk4vhr5x7urz525usl7xvjur35fsc6bmu",
    decimals: 7,
  },
  {
    code: "AQUA",
    issuer: "GBNZILSTVQZ4R7IKQDGHYGY2QXL5QOFJYQMXPKWRRM5PAV7Y4M67AQUA",
    contract: "CAUIKL3IYGMERDRUN6YSCLWVAKIFG5Q4YJHUKM4S4NJZQIA3BAS6OJPK",
    name: "AQUA Token",
    org: "Aquarius dba AQUA token",
    domain: "aqua.network",
    icon: "https://ipfs.io/ipfs/bafkreigzckkixvbkru2gzve67zu3bfauccugkr6zovkdv6h2yxxrppyyqa",
    decimals: 7,
  },
  {
    name: "Glo Dollar",
    code: "USDGLO",
    issuer: "GBBS25EGYQPGEZCGCFBKG4OAGFXU6DSOQBGTHELLJT3HZXZJ34HWS6XV",
    contract: "CB226ZOEYXTBPD3QEGABTJYSKZVBP2PASEISLG3SBMTN5CE4QZUVZ3CE",
    org: "Glo Development Foundation",
    domain: "app.glodollar.org",
    icon: "https://app.glodollar.org/glo-logo.png",
    decimals: 7,
  },
  {
    name: "The Blockchain Superfood",
    code: "KALE",
    issuer: "GBDVX4VELCDSQ54KQJYTNHXAHFLBCA77ZY2USQBM4CSHTTV7DME7KALE",
    contract: "CB23WRDQWGSP6YPMY4UV5C4OW5CBTXKYN3XEATG7KJEZCXMJBYEHOUOV",
    org: "The KALEpail Project",
    domain: "kalepail.com",
    icon: "https://imagedelivery.net/yd3qPvu7Jy_6BfgoQb2pZQ/30466c1d-ef73-4d2b-8814-949157465a00/public",
    decimals: 7,
  },
  {
    name: "yBTC by Ultra Capital",
    code: "yBTC",
    issuer: "GBUVRNH4RW4VLHP4C5MOF46RRIRZLAVHYGX45MVSTKA2F6TMR7E7L6NW",
    contract: "CB2XMFB6BDIHFOSFB5IXHDOYV3SI3IXMNIZLPDZHC7ENDCXSBEBZAO2Y",
    org: "Ultra Capital LLC",
    domain: "ultracapital.xyz",
    icon: "https://ipfs.io/ipfs/bafkreifuhpzfs5f6umrzrkqcspgvchruzwyuyvtgpzhs4nyvuraertoaby",
    decimals: 7,
  },
  {
    code: "GBPx",
    issuer: "GAVH5ZWACAY2PHPUG4FL3LHHJIYIHOFPSIUGM2KHK25CJWXHAV6QKDMN",
    contract: "CBCO65UOWXY2GR66GOCMCN6IU3Y45TXCPBY3FLUNL4AOUMOCKVIVV6JC",
    name: "Decentralized GBP Coin",
    org: "FxDAO LLC",
    domain: "fxdao.io",
    icon: "https://stellar.myfilebase.com/ipfs/QmeGXphMJgKHdhoVxb6P3jEJEkj79WPheLiga7ouNd5EZm",
    decimals: 7,
  },
  {
    name: "ETH by Ultra Capital",
    code: "ETH",
    issuer: "GBFXOHVAS43OIWNIO7XLRJAHT3BICFEIKOJLZVXNT572MISM4CMGSOCC",
    contract: "CBH4M45TQBLDPXOK6L7VYKMEJWFITBOL64BN3WDAIIDT4LNUTWTTOCKF",
    org: "Ultra Capital LLC",
    domain: "ultracapital.xyz",
    icon: "https://ipfs.io/ipfs/bafkreiad2di72p5p7bs3tolvimrq4bspcle3eqc74j7557wrqsnxlxlqya",
    decimals: 7,
  },
  {
    code: "SSLX",
    issuer: "GBHFGY3ZNEJWLNO4LBUKLYOCEK4V7ENEBJGPRHHX7JU47GWHBREH37UR",
    contract: "CBHBD77PWZ3AXPQVYVDBHDKEMVNOR26UZUZHWCB6QC7J5SETQPRUQAS4",
    name: "SSLX Cassator",
    org: "Cassator Corp.",
    domain: "sslx.sl8.online",
    icon: "https://ipfs.io/ipfs/bafkreiecqakv3lqychk6wwzccywywvtwjag3vtehzj4m3qilcj7735cfva",
    decimals: 7,
  },
  {
    code: "XRF",
    issuer: "GCHI6I3X62ND5XUMWINNNKXS2HPYZWKFQBZZYBSMHJ4MIP2XJXSZTXRF",
    contract: "CBLLEW7HD2RWATVSMLAGWM4G3WCHSHDJ25ALP4DI6LULV5TU35N2CIZA",
    name: "Reflector xRF",
    org: "Reflector",
    domain: "reflector.network",
    icon: "https://reflector.network/favicon-32x32.png",
    decimals: 7,
  },
  {
    code: "USTRY",
    issuer: "GCRYUGD5NVARGXT56XEZI5CIFCQETYHAPQQTHO2O3IQZTHDH4LATMYWC",
    contract: "CBLV4ATSIWU67CFSQU2NVRKINQIKUZ2ODSZBUJTJ43VJVRSBTZYOPNUR",
    name: "Etherfuse USTRY",
    org: "Etherfuse",
    domain: "etherfuse.com",
    icon: "https://stablebonds.s3.us-west-2.amazonaws.com/stablebond/spl-ustry.png",
    decimals: 7,
  },
  {
    code: "EURx",
    issuer: "GAVH5ZWACAY2PHPUG4FL3LHHJIYIHOFPSIUGM2KHK25CJWXHAV6QKDMN",
    contract: "CBN3NCJSMOQTC6SPEYK3A44NU4VS3IPKTARJLI3Y77OH27EWBY36TP7U",
    name: "Decentralized EUR Coin",
    org: "FxDAO LLC",
    domain: "fxdao.io",
    icon: "https://stellar.myfilebase.com/ipfs/QmTGegMR2v86ZjzHvhT3DMD6t1ri1VUz82tqRt4SxbFjC1",
    decimals: 7,
  },
  {
    code: "XRP",
    issuer: "GBVOL67TMUQBGL4TZYNMY3ZQ5WGQYFPFD5VJRWXR72VA33VFNL225PL5",
    contract: "CBPMFYWP4FFV7PQUYHXJZBXS75EHR6FXYSYEZWH2UM7AUYSKI2Z3PTCG",
    name: "Ripple",
    org: "unknown",
    domain: "stellarport.io",
    icon: "https://ipfs.io/ipfs/bafkreiheegvgfzbks6tacnlw24ub2frnr7j32rkzamieifhi2avljcly6m",
    decimals: 7,
  },
  {
    code: "YBX",
    issuer: "GBUYYBXWCLT2MOSSHRFCKMEDFOVSCAXNIEW424GLN666OEXHAAWBDYMX",
    contract: "CBRP2VD3CZLEQIQZ4JMBXGA5AC2U6JE26YU5CCIOICIZCVWPGBO2QRUB",
    name: "YieldBlox",
    org: "YieldBlox DAO",
    domain: "script3.io",
    icon: "https://uploads-ssl.webflow.com/607f603d2f412c67690368b8/60df683719cc056004ea932b_YBX%20token%20web%20bad.png",
    decimals: 7,
  },
  {
    name: "Poye",
    code: "POYE",
    issuer: "GCANJQJUFIWG7TXKCAJPG726KWW5CXISB2KM2MZRYLVV6AMZENZQN2ZE",
    contract: "CBT2U7I6J7LSEEJQQXBEOSRXNRNLH5UQPWG74Q36J3RHNQOQ5KEFCJ4Y",
    org: "Poye Network",
    domain: "poye.xyz",
    icon: "https://stellar.myfilebase.com/ipfs/QmYUeh7TRHB6bbBrZ2JLSsVEgww4fAHfPzaa7gFDDXrPB4",
    decimals: 7,
  },
  {
    code: "LSP",
    issuer: "GAB7STHVD5BDH3EEYXPI3OM7PCS4V443PYB5FNT6CFGJVPDLMKDM24WK",
    contract: "CBXE6V454EUYWVQCI4TCSOG4CSNPQ2BLYOTKAKXYFHO3KNVX4CXYCY2T",
    name: "Lumenswap asset",
    org: "Lumenswap LLC dba Lumenswap",
    domain: "lumenswap.io",
    icon: "https://ipfs.io/ipfs/bafkreiazthj4bttq75cxhgaekfxnv7ub6b2hq6qr5qkea4bhy4gie4qegy",
    decimals: 7,
  },
  {
    code: "NGNC",
    issuer: "GASBV6W7GGED66MXEVC7YZHTWWYMSVYEY35USF2HJZBLABLYIFQGXZY6",
    contract: "CBYFV4W2LTMXYZ3XWFX5BK2BY255DU2DSXNAE4FJ5A5VYUWGIBJDOIGG",
    name: "NGNC Coin",
    org: "LINK.IO LTD",
    domain: "ngnc.online",
    icon: "https://uploads-ssl.webflow.com/60a70a1080cf2974d4b1595e/61961ce43c530394bcb05349_NGRC.png",
    decimals: 7,
  },
  {
    code: "oUSD",
    issuer: "GBIWJGAOSFC4KUPHXM573TKTWHMI7VW7D4GCHYZYH243Q6HVBV7ORBIT",
    contract: "CBZPEXQLJCGUYTAQRQ4FGCXUV5O4TZER5WSOMCGNDNIIO4EJ4FU5GQNZ",
    name: "Orbit USD",
    org: "Orbit CDP",
    domain: "orbitcdp.finance",
    icon: "https://testnet.orbitcdp.finance/icons/tokens/ousd.svg",
    decimals: 7,
  },
  {
    name: "yXLM by Ultra Capital",
    code: "yXLM",
    issuer: "GARDNV3Q7YGT4AKSDF25LT32YSCCW4EV22Y2TV3I2PU2MMXJTEDL5T55",
    contract: "CBZVSNVB55ANF24QVJL2K5QCLOAB6XITGTGXYEAF6NPTXYKEJUYQOHFC",
    org: "Ultra Capital LLC",
    domain: "ultracapital.xyz",
    icon: "https://ipfs.io/ipfs/bafkreihntcz2lpaxawmbhwidtuifladkgew6olwuly2dz5pewqillhhpay",
    decimals: 7,
  },
  {
    code: "ARS",
    issuer: "GCYE7C77EB5AWAA25R5XMWNI2EDOKTTFTTPZKM2SR5DI4B4WFD52DARS",
    contract: "CCD6H4LBTHAPY3NGEE6TLLRUSPJGX4K5XI2J6E4MUNDB5TNXEKC23H5B",
    name: "ARS by Anclap",
    org: "Anclap",
    domain: "api.anclap.com",
    icon: "https://static.anclap.com/coin/ars.png",
    decimals: 7,
  },
  {
    code: "AFR",
    issuer: "GBX6YI45VU7WNAAKA3RBFDR3I3UKNFHTJPQ5F6KOOKSGYIAM4TRQN54W",
    contract: "CCG27OZ5AV4WUXS6XTECWAXEY5UOMEFI2CWFA3LHZGBTLYZWTJF3MJYQ",
    name: "AFREUM",
    org: "Afreum Inc dba Afreum",
    domain: "afreum.com",
    icon: "https://ipfs.io/ipfs/bafkreibwqfiennh5grnq2jx4632227sacotxyxww7jkfo2jblelnnqite4",
    decimals: 7,
  },
  {
    code: "SCOP",
    issuer: "GC6OYQJIZF3HFXCYPFCBXYXNGIBQ4TNSFUBUXQJOZWIP6F3YZK4QH3VQ",
    contract: "CCJVS6IVXAAXWCMFVK6QLWHZHR4RTVRSEZRQ53GOAEDN3VY2BLPVY72J",
    name: "Scopuly",
    org: "Scopuly",
    domain: "scopuly.com",
    icon: "https://ipfs.io/ipfs/bafkreigzc5scjuh2pry7j6eqnbao7irznrf7un5jj3fwhae3qseupvpska",
    decimals: 7,
  },
  {
    code: "SHX",
    issuer: "GDSTRSHXHGJ7ZIVRBXEYE5Q74XUVCUSEKEBR7UCHEUUEK72N7I7KJ6JH",
    contract: "CCKCKCPHYVXQD4NECBFJTFSCU2AMSJGCNG4O6K4JVRE2BLPR7WNDBQIQ",
    name: "Stronghold SHx",
    org: "Stronghold",
    domain: "stronghold.co",
    icon: "https://ipfs.io/ipfs/bafkreiafy5nqmyfy5t3ay5tgmy5wnzkqlyqkir2owjq4jqwcxklne4xqcm",
    decimals: 7,
  },
  {
    code: "USDC",
    issuer: "GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN",
    contract: "CCW67TSZV3SSS2HXMBQ5JFGCKJNXKZM7UQUWUZPUTHXSTZLEO7SJMI75",
    name: "USD Coin",
    org: "Centre Consortium LLC",
    domain: "centre.io",
    icon: "https://ipfs.io/ipfs/bafkreibpzncuhbk5ozhdw7xkcdoyf3xhwhcwcf6sj7axjzimxw6vm6pvyy",
    decimals: 7,
  },
  {
    code: "BLND",
    issuer: "GDJEHTBE6ZHUXSWFI642DCGLUOECLHPF3KSXHPXTSTJ7E3JF6MQ5EZYY",
    contract: "CD25MNVTZDL4Y3XBCPCJXGXATV5WUHHOWMYFF4YBEGU5FCPGMYTVG5JY",
    name: "Blend",
    org: "Blend Protocol",
    domain: "blend.capital",
    icon: "https://stellar.myfilebase.com/ipfs/QmaDc2ArxQom1bFkE7JsqqZ2VdThvLV2GTRimaeJcpxU8L",
    decimals: 7,
  },
  {
    code: "STROOPY",
    issuer: "GBZ3SMMNNSOLVV6LGNDBDWRVD2N56VUZZ6LVB6VGOOJGSMWI7ISLOJEC",
    contract: "CDDL6HGNYGVRCQB37DDFTIFYMGTX36AQMCXI6U3NOAO2BBZDNGKMGQSY",
    name: "STROOPY",
    org: "Silver Hen Tech",
    domain: "xlmeme.com",
    icon: "https://xlmeme.com/cdn-cgi/imagedelivery/BMsStEZme-xi9eCyEb_01g/bfb4bba0-00d6-434b-ea8a-89d733dcd000/public",
    decimals: 7,
  },
  {
    code: "USDx",
    issuer: "GAVH5ZWACAY2PHPUG4FL3LHHJIYIHOFPSIUGM2KHK25CJWXHAV6QKDMN",
    contract: "CDIKURWHYS4FFTR5KOQK6MBFZA2K3E26WGBQI6PXBYWZ4XIOPJHDFJKP",
    name: "Decentralized USD Coin",
    org: "FxDAO LLC",
    domain: "fxdao.io",
    icon: "https://stellar.myfilebase.com/ipfs/QmQqpy1GLcGqqsg6DaHqLQntPPuFcdHZYG2pLBpHohvCUd",
    decimals: 7,
  },
  {
    name: "yUSDC",
    code: "yUSDC",
    issuer: "GDGTVWSM4MGS4T7Z6W4RPWOCHE2I6RDFCIFZGS3DOA63LWQTRNZNTTFF",
    contract: "CDOFW7HNKLUZRLFZST4EW7V3AV4JI5IHMT6BPXXSY2IEFZ4NE5TWU2P4",
    org: "Ultra Capital LLC",
    domain: "ultracapital.xyz",
    icon: "https://ipfs.io/ipfs/bafkreicvkevokwxgvqn6vjmf4hf2krk6txy3igi7ei6dwvleb5hqe4odcy",
    decimals: 7,
  },
  {
    code: "EURC",
    issuer: "GDHU6WRG4IEQXM5NZ4BMPKOXHW76MZM4Y2IEMFDVXBSDP6SJY4ITNPP2",
    contract: "CDTKPWPLOURQA2SGTKTUQOWRCBZEORB4BWBOMJ3D3ZTQQSGE5F6JBQLV",
    name: "EUR Coin",
    org: "Circle Internet Financial, LLC",
    domain: "circle.com",
    icon: "https://ipfs.io/ipfs/bafkreidizqlammdzrrurfq3o5owta77fiyonn6ri72h6rltqimn2xs2by4",
    decimals: 7,
  },
  {
    name: "yETH By Ultra Capital",
    code: "yETH",
    issuer: "GDYQNEF2UWTK4L6HITMT53MZ6F5QWO3Q4UVE6SCGC4OMEQIZQQDERQFD",
    contract: "CDYEOOVL6WV4JRY45CXQKOBJFFAPOM5KNQCCDNM333L6RM2L4RO3LKYG",
    org: "Ultra Capital LLC",
    domain: "ultracapital.xyz",
    icon: "https://ipfs.io/ipfs/bafkreihqsw7iai5gcfwvgnexdcwvftiv7fjjbg2skc2wcdygfngllv5ute",
    decimals: 7,
  },
];

function combineList(primary, secondary) {
  const seen = new Set();
  const result = [];
  const add = (arr) => {
    for (const item of arr) {
      const key = String(item.contract || "")
        .trim()
        .toUpperCase();
      if (!key) continue;
      if (seen.has(key)) continue;
      seen.add(key);
      result.push(item);
    }
  };
  add(primary);
  add(secondary);

  return result;
}

const curratedList = combineList(stellarAssets, soroswapList);

module.exports = { curratedList };
